//! Interior furniture tiles.

use super::SpriteDef;

pub static PROP_RUG: SpriteDef = SpriteDef {
    name: "prop_rug",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "pppppppppppppppp\n",
        "pYYYYYYYYYYYYYYp\n",
        "pYppppppppppppYp\n",
        "pYpYYYYYYYYYYpYp\n",
        "pYpY........YpYp\n",
        "pYpY........YpYp\n",
        "pYpY........YpYp\n",
        "pYpY........YpYp\n",
        "pYpY........YpYp\n",
        "pYpY........YpYp\n",
        "pYpYYYYYYYYYYpYp\n",
        "pYppppppppppppYp\n",
        "pYYYYYYYYYYYYYYp\n",
        "pppppppppppppppp\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_TABLE: SpriteDef = SpriteDef {
    name: "prop_table",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "................\n",
        ".ZZZZZZZZZZZZZ..\n",
        ".ZYYYYYYYYYYYZ..\n",
        ".ZYYYYYYYYYYYZ..\n",
        ".ZZZZZZZZZZZZZ..\n",
        ".Z...........Z..\n",
        ".Z...........Z..\n",
        ".Z...........Z..\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_BED: SpriteDef = SpriteDef {
    name: "prop_bed",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "................\n",
        ".FFFFFFFFFFFF...\n",
        ".FEEEEEEEEEEF...\n",
        ".FEEEEEEEEEEF...\n",
        ".FuuuuuuuuuuF...\n",
        ".FvvvvvvvvvvF...\n",
        ".FvvvvvvvvvvF...\n",
        ".FvvvvvvvvvvF...\n",
        ".FFFFFFFFFFFF...\n",
        ".ZZ........ZZ...\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_SHELF: SpriteDef = SpriteDef {
    name: "prop_shelf",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "ZZZZZZZZZZZZZZZZ\n",
        "Z..............Z\n",
        "Z.BB.oo.uu.BB..Z\n",
        "Z..............Z\n",
        "ZZZZZZZZZZZZZZZZ\n",
        "Z..............Z\n",
        "Z.pp.AA.vv.pp..Z\n",
        "Z..............Z\n",
        "ZZZZZZZZZZZZZZZZ\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_COUNTER: SpriteDef = SpriteDef {
    name: "prop_counter",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "................\n",
        "YYYYYYYYYYYYYYYY\n",
        "YZZZZZZZZZZZZZZY\n",
        "YZ............ZY\n",
        "YZ............ZY\n",
        "YZ............ZY\n",
        "YZZZZZZZZZZZZZZY\n",
        "YYYYYYYYYYYYYYYY\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_POT: SpriteDef = SpriteDef {
    name: "prop_pot",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "................\n",
        ".....gggg.......\n",
        "....ghhhhg......\n",
        "....gh...hg.....\n",
        "....ghhhhhg.....\n",
        ".....gggg.......\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};
