//! Phase 2C puzzle / bomb prop sprites (indexed grids).

use super::SpriteDef;

pub static PROP_GATE: SpriteDef = SpriteDef {
    name: "prop_gate",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "hhhhhhhhhhhhhhhh\n",
        "hZZZZZZZZZZZZZZh\n",
        "hZ............Zh\n",
        "hZ.hhhh..hhhh.Zh\n",
        "hZ.hhhh..hhhh.Zh\n",
        "hZ.hhhh..hhhh.Zh\n",
        "hZ.hhhh..hhhh.Zh\n",
        "hZ............Zh\n",
        "hZZZZZZZZZZZZZZh\n",
        "hhhhhhhhhhhhhhhh\n",
        "h..............h\n",
        "h..............h\n",
        "h..............h\n",
        "h..............h\n",
        "h..............h\n",
        "hhhhhhhhhhhhhhhh\n",
    ),
};

pub static PROP_BLOCK: SpriteDef = SpriteDef {
    name: "prop_block",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "..hhhhhhhhhhhh..\n",
        ".hWWWWWWWWWWWWh.\n",
        "hW..........WWh.\n",
        "hW.h......h.WWh.\n",
        "hW..........WWh.\n",
        "hW....hh....WWh.\n",
        "hW..........WWh.\n",
        "hW.h......h.WWh.\n",
        "hW..........WWh.\n",
        "hWWWWWWWWWWWWWh.\n",
        ".hhhhhhhhhhhhh..\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_PLATE_UP: SpriteDef = SpriteDef {
    name: "prop_plate_up",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "................\n",
        "................\n",
        "..hhhhhhhhhhhh..\n",
        ".hZZZZZZZZZZZZh.\n",
        ".hZ..........Zh.\n",
        ".hZ..AAAAAA..Zh.\n",
        ".hZ..AAAAAA..Zh.\n",
        ".hZ..........Zh.\n",
        ".hZZZZZZZZZZZZh.\n",
        "..hhhhhhhhhhhh..\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_PLATE_DOWN: SpriteDef = SpriteDef {
    name: "prop_plate_down",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "................\n",
        "................\n",
        "................\n",
        "..hhhhhhhhhhhh..\n",
        ".hZZZZZZZZZZZZh.\n",
        ".hZ..........Zh.\n",
        ".hZ..hhhhhh..Zh.\n",
        ".hZ..........Zh.\n",
        ".hZZZZZZZZZZZZh.\n",
        "..hhhhhhhhhhhh..\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_BARRICADE: SpriteDef = SpriteDef {
    name: "prop_barricade",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "..Z..Z....Z..Z..\n",
        ".ZhhZhh..hhZhhZ.\n",
        "Zhhhhhh..hhhhhhZ\n",
        "Zhh..hh..hh..hhZ\n",
        "Zhhhhhh..hhhhhhZ\n",
        ".ZhhZhh..hhZhhZ.\n",
        "..Z..Z....Z..Z..\n",
        "ZhhhhhhhhhhhhhhZ\n",
        "Zhh..hhXX..hhhhZ\n",
        "ZhhhhhhhhhhhhhhZ\n",
        ".Z............Z.\n",
        "..Z..........Z..\n",
        "................\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_CRANK: SpriteDef = SpriteDef {
    name: "prop_crank",
    w: 16,
    h: 16,
    frames: 2,
    grid: concat!(
        "................................\n",
        "......hhhh............hhhh......\n",
        "....hhAAAAhh........hhAAAAhh....\n",
        "...hAA....AAh......hAA....AAh...\n",
        "...hA..hh..Ah......hA..AA..Ah...\n",
        "...hA..hh..Ah......hA..AA..Ah...\n",
        "...hAA....AAh......hAA....AAh...\n",
        "....hhAAAAhh........hhAAAAhh....\n",
        "......hhhh............hhhh......\n",
        ".......ZZ..............ZZ.......\n",
        "......ZZZZ............ZZZZ......\n",
        "................................\n",
        "................................\n",
        "................................\n",
        "................................\n",
        "................................\n",
    ),
};

/// Darker bridge plank (reuses bridge silhouette, wood-dark row).
pub static PROP_BRIDGE_LOWERED: SpriteDef = SpriteDef {
    name: "prop_bridge_lowered",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
        "hhhhhhhhhhhhhhhh\n",
        "hZZZZZZZZZZZZZZh\n",
        "hZhhhhhhhhhhhhZh\n",
        "hZ............Zh\n",
        "hZhhhhhhhhhhhhZh\n",
        "hZ............Zh\n",
        "hZhhhhhhhhhhhhZh\n",
        "hZ............Zh\n",
        "hZhhhhhhhhhhhhZh\n",
        "hZ............Zh\n",
        "hZhhhhhhhhhhhhZh\n",
        "hZZZZZZZZZZZZZZh\n",
        "hhhhhhhhhhhhhhhh\n",
        "................\n",
        "................\n",
        "................\n",
    ),
};

pub static PROP_BOMB: SpriteDef = SpriteDef {
    name: "prop_bomb",
    w: 16,
    h: 16,
    frames: 2,
    grid: concat!(
        "................................\n",
        ".......AA.............AA........\n",
        "......A..A...........A..A.......\n",
        ".......FF.............oo........\n",
        ".....hhhhhh.........hhhhhh......\n",
        "....hhFFFFFFh......hhooooooh....\n",
        "...hhFFFFFFFhh....hhooooooooh...\n",
        "...hFFFFFFFFFh....hoooooooooh...\n",
        "...hFFFFFFFFFh....hoooooooooh...\n",
        "...hhFFFFFFFhh....hhooooooooh...\n",
        "....hhFFFFFFh......hhooooooh....\n",
        ".....hhhhhh.........hhhhhh......\n",
        "................................\n",
        "................................\n",
        "................................\n",
        "................................\n",
    ),
};
