//! Forest canopy plus structure shells (16×16).

use super::SpriteDef;

pub static TILE_TREE_TRUNK: SpriteDef = SpriteDef {
    name: "tree_trunk",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "................\n",
    "................\n",
    "................\n",
    "....FFFFF.......\n",
    ".....tttttt.....\n",
    ".....tttttt.....\n",
    "....SttttttS....\n",
    "....SttttttS....\n",
    "....SttttttS....\n",
    "....SttttttS....\n",
    "....SttttttS....\n",
    ".....tttttt.....\n",
    ".....SSSSSS.....\n",
    ".....SSSSSS.....\n",
    ".....SSSSSS.....\n",
    ".....SSSSSS.....\n",
    ),
};

pub static TILE_CANOPY_NW: SpriteDef = SpriteDef {
    name: "canopy_nw",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "................\n",
    "................\n",
    "................\n",
    "..........FFFFF.\n",
    ".......FFF66666F\n",
    "......FF66666666\n",
    ".....FF666677766\n",
    "....FF6667777777\n",
    "....F66677777777\n",
    "....F66777777777\n",
    "...F666777777777\n",
    "...F667777777777\n",
    "...F667777777777\n",
    "...F667777777777\n",
    "...F666777777777\n",
    "....F66777777777\n",
    ),
};

pub static TILE_CANOPY_NE: SpriteDef = SpriteDef {
    name: "canopy_ne",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "................\n",
    "................\n",
    "................\n",
    "..FFFFF.........\n",
    "FF66666FFF......\n",
    "666666666FF.....\n",
    "6667776666FF....\n",
    "67777777666FF...\n",
    "777777777666F...\n",
    "777777777766F...\n",
    "7777777777666F..\n",
    "7777777777766F..\n",
    "7777777777766F..\n",
    "7777777777766F..\n",
    "7777777777666F..\n",
    "777777777766F...\n",
    ),
};

pub static TILE_CANOPY_SW: SpriteDef = SpriteDef {
    name: "canopy_sw",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "....F66677777777\n",
    "....F66777777777\n",
    "...F666777777777\n",
    "...F667777777777\n",
    "...F667777777777\n",
    "...F667777777777\n",
    "...F666777777777\n",
    "....F66777777777\n",
    "....F66677777777\n",
    "....FF6667777777\n",
    ".....FF666677766\n",
    "......FF66666666\n",
    ".......FFF66666F\n",
    "..........FFFFF.\n",
    "................\n",
    "................\n",
    ),
};

pub static TILE_CANOPY_SE: SpriteDef = SpriteDef {
    name: "canopy_se",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "777777777666F...\n",
    "777777777766F...\n",
    "7777777777666F..\n",
    "7777777777766F..\n",
    "7777777777766F..\n",
    "7777777777766F..\n",
    "7777777777666F..\n",
    "777777777766F...\n",
    "777777777666F...\n",
    "67777777666FF...\n",
    "6667776666FF....\n",
    "666666666FF.....\n",
    "FF66666FFF......\n",
    "..FFFFF.........\n",
    "................\n",
    "................\n",
    ),
};

pub static TILE_BRIDGE_H: SpriteDef = SpriteDef {
    name: "bridge_h",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "FFFFFFFFFFFFFFFF\n",
    "FZZZZOZZZZtZZZZF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZOZZZZZZZZZZZF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZZZZZZZZZZZOZF\n",
    "FZZZZZZZZOZZZOZF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZOZZZZZZZZZZZF\n",
    "FZZZZZtZZZZZZZtF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZZtZZZZZZZZZZF\n",
    "FZZOZOZZZZZZZZZF\n",
    "FZZZZOZZZZZZZZZF\n",
    "FZZZZZZZZZZOZZZF\n",
    "FFFFFFFFFFFFFFFF\n",
    ),
};

pub static TILE_BRIDGE_V: SpriteDef = SpriteDef {
    name: "bridge_v",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "FFFFFFFFFFFFFFFF\n",
    "FZOZZZOZZZZZZZZF\n",
    "FZZZOZZZZZZZZZZF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZZZZZZZZZZZtOF\n",
    "FZZtZZZZOZZZZZZF\n",
    "FZZZZZZtZZZZZZOF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZZZZZZOZZZZZZF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZZZZZtZZZZZZZF\n",
    "FZZZZZZZZZZZZZZF\n",
    "FZZZZZZZZZOZZZZF\n",
    "FZZZZtZZZZZZZZZF\n",
    "FFFFFFFFFFFFFFFF\n",
    ),
};

pub static TILE_BRIDGE_BROKEN: SpriteDef = SpriteDef {
    name: "bridge_broken",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "ZZZZZZZZZZZZZZGZ\n",
    "ZZZZZZZZZZZZZZZZ\n",
    "ZZGZZZZZZZZZZZZk\n",
    "ZZZZZZZZZZZZZZZZ\n",
    "GZZZZZZZZZZZZZZZ\n",
    "ZZGZZZZZZZZZZkZZ\n",
    "ZZZZZZZZZZZZZZZZ\n",
    "ZZZZZZZZZZZZZZZZ\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    ),
};

pub static TILE_FENCE: SpriteDef = SpriteDef {
    name: "fence",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "tttttttttttttttt\n",
    "tttttttttttttttt\n",
    "tS..tS..tS..tS..\n",
    "tS..tS..tS..tS..\n",
    "tS..tS..tS..tS..\n",
    "tS..tS..tS..tS..\n",
    "tttttttttttttttt\n",
    "tttttttttttttttt\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    ),
};

pub static TILE_SHRINE_STONE: SpriteDef = SpriteDef {
    name: "shrine_stone",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "FFFFFFFFFFFFFFFF\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gggggggghghggggg\n",
    "gggggggggggggggi\n",
    "gigggggggggggFgg\n",
    "gggggggggggggggg\n",
    "gggggggggghgghgg\n",
    "ghggFggggggggggg\n",
    "gggggggggggggggg\n",
    "gFghggggggggiigg\n",
    "ggggggggghgggggg\n",
    "ggggggggggghgggg\n",
    "gggggggggggggggg\n",
    "igghggiggFgggggg\n",
    "FFFFFFFFFFFFFFFF\n",
    ),
};

pub static TILE_DOOR_SEALED: SpriteDef = SpriteDef {
    name: "door_sealed",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "jjjjjjjjjjjFkjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjkkkBBkkkjjjj\n",
    "jjjjkkkBBkkkjjjj\n",
    "jjjjkkkBBkkkjjjj\n",
    "jjjjkkkBBkkkjFjj\n",
    "jjjjkkkBBkkkjjjj\n",
    "jjjjkkkBBkkkjjjj\n",
    "kjjjkkkBBkkkjjjj\n",
    "jjjjkkkBBkkkjjjj\n",
    "jjjFkkkBBkkkjjjj\n",
    "kjkjkkkBBkkkjjjj\n",
    "jjjFkkkBBkkkjjjj\n",
    "jjjjkkkBBkkkjjkj\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    ),
};

pub static TILE_CAVE_MOUTH: SpriteDef = SpriteDef {
    name: "cave_mouth",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "kkkkkkkkkkkkkkkk\n",
    "kkkkkkkjkkkkkkkk\n",
    "kkkkkkkjkjkkkjkk\n",
    "kkkkkkkkkkkkkkGk\n",
    ".....kkGGGkk....\n",
    "....kGGGGGGGk...\n",
    "...kGGGGGGGGG...\n",
    "...kGGGGGGGGG...\n",
    "...GGGGGGGGGG...\n",
    "...GGGGGGGGGG...\n",
    "...GGGGGGGGGG...\n",
    "...kGGGGGGGGG...\n",
    "...kGGGGGGGGG...\n",
    "....kGGGGGGGk...\n",
    "kkkkkkkkkkkkGkkk\n",
    "kjkkkkkkkkGjkkkk\n",
    ),
};

pub static TILE_HOUSE_WALL: SpriteDef = SpriteDef {
    name: "house_wall",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "ihhhhhhhhhhhihhh\n",
    "hhihhhihhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "ihhhhhhhhhhhhghh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhgihhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhihhhhhhhhghhhh\n",
    "hhihihhhhhhhhghh\n",
    "hhihhhhhhhhhhhih\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    ),
};

pub static TILE_HOUSE_DOOR: SpriteDef = SpriteDef {
    name: "house_door",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhttBttthhhhh\n",
    "hhhhhttBtttihihh\n",
    "hhhihttBttthhhhh\n",
    "hhhhhttBttthghhi\n",
    "hhhhhttBttthhhhh\n",
    "hhhhhttBttthhhhh\n",
    "hhhhhttBttthhhhh\n",
    "hhhhhttBttthhihh\n",
    "hhghhttBttthhhhh\n",
    "hhhhhttBttthhhhh\n",
    "hhhhhttBttthhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    ),
};

pub static TILE_COLUMN: SpriteDef = SpriteDef {
    name: "column",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "....FggggggF....\n",
    "....FggggggF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FhhhhhhF....\n",
    "....FggggggF....\n",
    "....FggggggF....\n",
    ),
};

pub static TILE_ARCH_TOP: SpriteDef = SpriteDef {
    name: "arch_top",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    ".ggggggggggggggg\n",
    "..ggggggggggggg.\n",
    "...ggggggggggg..\n",
    "....ggggggggg...\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    "................\n",
    ),
};

pub static TILE_INT_FLOOR: SpriteDef = SpriteDef {
    name: "int_floor",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "lllllmllllllllll\n",
    "llmmllllllllllll\n",
    "llllllllllllllll\n",
    "llllllllllllllll\n",
    "llllllllllllllll\n",
    "lllllllllllllmll\n",
    "lllllmllllllmlll\n",
    "llllllllllllllll\n",
    "lllllllllllllmll\n",
    "llllmlllllllllll\n",
    "llllllllmllmllll\n",
    "llllllllllllllll\n",
    "lllllllllllmllll\n",
    "llllllllllllllll\n",
    "lllllmllllllllll\n",
    "lllmllllllllllll\n",
    ),
};

pub static TILE_INT_WALL: SpriteDef = SpriteDef {
    name: "int_wall",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "nnnnnnnnnnnnnnnn\n",
    "nnnnnnnnnnnnnnnn\n",
    "nnnnnnnnnnnnnnnn\n",
    "nnnnnnnnnnnnnnnn\n",
    "hhjhhhhhhhhhhhhh\n",
    "hhhhhhihhhhhhihh\n",
    "hkhhhhhhhhhhhhhh\n",
    "hhhhhhhhhkhhhkhh\n",
    "hhhhhhhhhhhhkhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hkhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhihhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhihhhhhh\n",
    "hhhhhhhhhhhhhhhj\n",
    ),
};

