//! Arena tile sheets (16×16).

use super::SpriteDef;


pub static TILE_FLOOR_A: SpriteDef = SpriteDef {
    name: "floor_a",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
    "4lllll5l4lllllll\n",
    "llll7llll6lllll5\n",
    "l6lllll5lllll7ll\n",
    "llllllllll6lllll\n",
    "ll6l4lll5lll4lll\n",
    "5llllllllll6llll\n",
    "lll6lllll5llllll\n",
    "l5llllllllll6lll\n",
    "4lll6lll4l5lllll\n",
    "ll5llllllllll6ll\n",
    "7llll6lllll5llll\n",
    "lll5lllll7llll6l\n",
    "llll4l6lllll4lll\n",
    "llll5llllllllll6\n",
    "lllllll6lllll5ll\n",
    "lllll5llllllllll\n",
    ),
};

pub static TILE_FLOOR_B: SpriteDef = SpriteDef {
    name: "floor_b",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
    "mmjmhmmmlmmmhmim\n",
    "lmmmmmmmmmmjmmmm\n",
    "mmmjmmmmmlmmmmmm\n",
    "mlmmmmmmmmmmjmmm\n",
    "hmmmjmmmhmlmmmmm\n",
    "mmlmmmmmmmmmmjmm\n",
    "mmmmmjmmmmmlmmmm\n",
    "mmmlmmmmmmmmmmjm\n",
    "mimmhmjmmmmmhmmm\n",
    "mmmmlmmmmmimmmmj\n",
    "mmmmmmmjmmmmmlmm\n",
    "mmmmmlmmmmmmmmmm\n",
    "hmmmmmmmhmmmmmlm\n",
    "jmmmmmlmmmmmmmmm\n",
    "mmmmmmmmmjmmmmml\n",
    "mjmmmmmlmmmmmmmm\n",
    ),
};

pub static TILE_WALL_TOP: SpriteDef = SpriteDef {
    name: "wall_top",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "nnnnnnnnnnnnnnnn\n",
    "nnninnnninnninnn\n",
    "nnninnnninnninnn\n",
    "nnninnnninnninnn\n",
    "nnninnnninnninnn\n",
    "nnninnnninnninnn\n",
    "nnninnnninnninnn\n",
    "nnninnnninnninnn\n",
    "nnnnnnnnnnnnnnnn\n",
    "nnnnnnnnnnnnnnnn\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    ),
};

pub static TILE_WALL_FACE: SpriteDef = SpriteDef {
    name: "wall_face",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
    "hhhhhhhjhhhhhhhh\n",
    "hhhhhhhjhhhhhhhh\n",
    "hhhhhhhjhhhhhhhh\n",
    "hhhhhhhjhhhhhhhh\n",
    "iiiiiiijiiiiiiii\n",
    "jjjjjjjjjjjjjjjj\n",
    "iiiiiiijiiiiiiii\n",
    "iiiiiiijiiiiiiii\n",
    "iiiiiiijiiiiiiii\n",
    "jjjjjjjjjjjjjjjj\n",
    "iiiiiiijiiiiiiii\n",
    "iiiiiiijiiiiiiii\n",
    "kkkkkkkjkkkkkkkk\n",
    "kkkkkkkjkkkkkkkk\n",
    "kkkkkkkjkkkkkkkk\n",
    "kkkkkkkjkkkkkkkk\n",
    ),
};

pub static TILE_FOUNTAIN: SpriteDef = SpriteDef {
    name: "fountain",
    w: 16,
    h: 16,
    frames: 2,
    grid: concat!(
    "................................\n",
    "................................\n",
    "......FFFF............FFFF......\n",
    ".....FxxxxF..........FxxxxF.....\n",
    "....FzzzzzzF........FzzzzzzF....\n",
    "....Fzz8zzzF........FzzuzzzF....\n",
    "....FzzzzzzF........FzzzzzzF....\n",
    "....Fzzz8zzF........FzzzuzzF....\n",
    "...FFz8zzzzFF......FFzxzzzzFF...\n",
    "..FggzzzzzzggF....FggzzzzzzggF..\n",
    ".FhhhhhhhhhhhhF..FhhhhhhhhhhhhF.\n",
    ".FhhhhhhhhhhhhF..FhhhhhhhhhhhhF.\n",
    ".FhhhhhhhhhhhhF..FhhhhhhhhhhhhF.\n",
    ".FhhhhhhhhhhhhF..FhhhhhhhhhhhhF.\n",
    ".FhhjjjjjjjjhhF..FhhjjjjjjjjhhF.\n",
    "..FFjjjjjjjjFF....FFjjjjjjjjFF..\n",
    ),
};

pub static TILE_PILLAR: SpriteDef = SpriteDef {
    name: "pillar",
    w: 16,
    h: 16,
    frames: 1,
    grid: concat!(
    "...FFFFFFFFFF...\n",
    "..FggggggggggF..\n",
    "..FggggggggggF..\n",
    "...FhhhhhhhhF...\n",
    "...FhgghhiihF...\n",
    "...FhgghhiihF...\n",
    "...FhgghhiihF...\n",
    "...FhgghhiihF...\n",
    "...FhgghhiihF...\n",
    "...FhgghhiihF...\n",
    "...FhgghhiihF...\n",
    "...FhgghhiihF...\n",
    "...FhhhhhhhhF...\n",
    "..FjjjjjjjjjjF..\n",
    "..FjjjjjjjjjjF..\n",
    "...FFFFFFFFFF...\n",
    ),
};
