//! Overworld terrain and cliffs (16×16).

use super::SpriteDef;

pub static TILE_GRASS_A: SpriteDef = SpriteDef {
    name: "grass_a",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "5566555456555555\n",
    "5555555555555555\n",
    "5555555555555555\n",
    "5555555575545555\n",
    "5555555555555555\n",
    "5555555545555555\n",
    "5555555575555555\n",
    "5555555555555555\n",
    "4555555555555555\n",
    "5555575555555555\n",
    "5555555755575555\n",
    "7555555555555555\n",
    "4555555555555555\n",
    "5455565555555555\n",
    "5555555555555555\n",
    "5555555555555555\n",
    ),
};

pub static TILE_GRASS_B: SpriteDef = SpriteDef {
    name: "grass_b",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "6666666666666666\n",
    "6666666667666566\n",
    "6676666666666666\n",
    "6666466666666666\n",
    "6666666666666667\n",
    "6466666666666666\n",
    "6666666666644666\n",
    "6666666666666666\n",
    "6665466666666666\n",
    "7666656665666646\n",
    "6666666666767666\n",
    "6666666666666666\n",
    "6656666666666666\n",
    "6666666666666666\n",
    "6666666666666666\n",
    "6666666666765666\n",
    ),
};

pub static TILE_GRASS_FLOWER: SpriteDef = SpriteDef {
    name: "grass_flower",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "555555555D555555\n",
    "5555575555555555\n",
    "5555555555555555\n",
    "555D555555555555\n",
    "5555555555555555\n",
    "5555555555555555\n",
    "5555555555755555\n",
    "5555555D7D555555\n",
    "5555555555554555\n",
    "5555575555555557\n",
    "5555555555555555\n",
    "55D5555555555555\n",
    "5575555D55555455\n",
    "555555555D555555\n",
    "5555D55555555555\n",
    "5455555555555554\n",
    ),
};

pub static TILE_GRASS_PEBBLE: SpriteDef = SpriteDef {
    name: "grass_pebble",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "i55555555555555h\n",
    "5555555555555555\n",
    "555555h555555h55\n",
    "5555555555555555\n",
    "55555g5555555555\n",
    "55555i5555555555\n",
    "55555555555555i5\n",
    "5555i55555555555\n",
    "555555ghg5555555\n",
    "55555i555555555i\n",
    "5555555555555555\n",
    "5555555555555h55\n",
    "555555555555g555\n",
    "555555i5i5555555\n",
    "h5i555555i5i5555\n",
    "5555555555555555\n",
    ),
};

pub static TILE_PATH: SpriteDef = SpriteDef {
    name: "path",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWtWWWXWWWWW\n",
    "WWWWWWXWWOWtWWWW\n",
    "WWWWOWWWWWWWWWWW\n",
    "WWWWWWWWWWOWWWWW\n",
    "WWWWWOWWOWWWWWWW\n",
    "WWWWWWWWWWXWWWWW\n",
    "WWXWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWOWW\n",
    "WWWWXWWWWWWWWWWW\n",
    "WWWWWWWWOWWWWWWW\n",
    ),
};

pub static TILE_PATH_N: SpriteDef = SpriteDef {
    name: "path_n",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "5555555555555555\n",
    "55WWWWWWWWWWWW55\n",
    "WWWXWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWXWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "XWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWXWWWXXWWWWW\n",
    "WWWXWXWWWWWXWWWW\n",
    "WWXXWWWXWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWXWWWW\n",
    "WWWXWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWXW\n",
    "WWWWWWWWWWWWWWXW\n",
    ),
};

pub static TILE_PATH_S: SpriteDef = SpriteDef {
    name: "path_s",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "WWWWWWXWXWWWWWWW\n",
    "WWWWWWWWWXXWXWWW\n",
    "WXWWXWWWWWXWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWXWWWXWWWWW\n",
    "WWWWWWWXWWWXWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WXWWWWWWXWWWWWWW\n",
    "WWXWWWWXWWWWWWWW\n",
    "XWWWWWWWWWWWWWWW\n",
    "WWWXWWWWWWWWWWWW\n",
    "WWWXWWWWXWWWWWWW\n",
    "XWWWWWXWWXWWWWXW\n",
    "XWWWWXXWWWWWXWWW\n",
    "55WWWWWWWWWWWW55\n",
    "5555555555555555\n",
    ),
};

pub static TILE_PATH_E: SpriteDef = SpriteDef {
    name: "path_e",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "WWWWWWWWWWWWWX55\n",
    "XWWWWWXWWWWWWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "WWWWWWWWXWWWWW55\n",
    "WWWXWWWWWWWWWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "XWWWWWWWWWWXWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "XWWWWWWWWWWWWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "WXWWWWWWWWXWWW55\n",
    "WWWWWWWWWWWWWW55\n",
    "WWWWWWWWWWWWWX55\n",
    ),
};

pub static TILE_PATH_W: SpriteDef = SpriteDef {
    name: "path_w",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "55WWWWWXWWWWWWWW\n",
    "55WWWWWWWWWWWWXX\n",
    "55WWWWWWWWWWWWWW\n",
    "55WWWWWWWWWWWWWW\n",
    "55WWWWWXWWWWWWWW\n",
    "55WWWWWWWWWWWWWW\n",
    "55WXWWWWWWWWWWWW\n",
    "55WWWWWWWXWWWWWW\n",
    "55WWWWWWWWWWWWWW\n",
    "55WWWWWWWWWWWWWW\n",
    "55WWWWWWXWWWWWWW\n",
    "55WWWWWWWXWWWWWW\n",
    "55WWWWWWWWWWWWWW\n",
    "55WWWWWWWWWWWWWW\n",
    "55WWXWWWWWWWWWWW\n",
    "55WWWWWWWWWWXWWW\n",
    ),
};

pub static TILE_DIRT: SpriteDef = SpriteDef {
    name: "dirt",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "WWWWWWWWWWtWtWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWtW\n",
    "WWWWWWWWWWWWWWWX\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWOWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWOWWWWWtWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WOWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWWWWW\n",
    "WWWWWWWWWWWWOWWW\n",
    "WWWWWWWWWWWWWWOW\n",
    "WWWWtWWWWWWWWWWW\n",
    ),
};

pub static TILE_DIRT_ASH: SpriteDef = SpriteDef {
    name: "dirt_ash",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "XXXXXXGXXXXWXXGX\n",
    "XXXXXXXXXXXXXXXX\n",
    "XXXXXXXXXXXXXXXX\n",
    "XXXXXXXXXXXXXXXX\n",
    "GXXXXXXXXXXXXXXX\n",
    "XXXXXXXXXXXXXXXX\n",
    "XXXXXXXXXXXXXXXX\n",
    "XXXXXXXXXXXXXXXX\n",
    "XXXXXWXXXXXXXXXX\n",
    "XXXXXXXXXXXXGXXX\n",
    "XWXXXXXXXXXXXXXX\n",
    "XXXXXXXXXXXGkXXX\n",
    "XXXXXXXXXXXXXXXX\n",
    "XXXXXXXXXXWXXXGX\n",
    "XXXXWXXXXXXXXXXX\n",
    "XXXkXXXXXXXXXXXX\n",
    ),
};

pub static TILE_SAND: SpriteDef = SpriteDef {
    name: "sand",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "YYYYYYYYYYYYYYYY\n",
    "YYYYYYYYYgYBYYYY\n",
    "YYYYYBYYYYYYYYgY\n",
    "YgYYYYBYYYYYBYYY\n",
    "YYYWYYYYYYYBYYYY\n",
    "YYYYYYYYYYYYYYYY\n",
    "YYYYYWYYYYYYYYYY\n",
    "YYYYYYYYYYYYYYYY\n",
    "YYYYYYYYYYYYYYYY\n",
    "WYBYYYYYYYYYYBYY\n",
    "YYYYYYYYYYYYYYYY\n",
    "YYYYYBYYYYYYYYYY\n",
    "YYYYYYYYYYYYYYYY\n",
    "YYYYYYYYYYYYYYYY\n",
    "YYYYYYYYYYYYYYYY\n",
    "WYYYYYYYYYYYYYYY\n",
    ),
};

pub static TILE_CLIFF_TOP: SpriteDef = SpriteDef {
    name: "cliff_top",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gggggggggggjgggg\n",
    "ghhggigggggggggg\n",
    "gggggggghghggjgg\n",
    "gggggggggggggggg\n",
    "ggggggggggggiigg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "ghggjggigggggggg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "ggggggggggjggggg\n",
    "gggggggggggggggg\n",
    ),
};

pub static TILE_CLIFF_FACE: SpriteDef = SpriteDef {
    name: "cliff_face",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "hhhhhhhhhhhhhhhh\n",
    "iiiiiiiiiiiiiiii\n",
    "iiiiiiiiiiiiiiii\n",
    "iiiiiiiiiiiiiiii\n",
    "iiiiiiiiiiiiiiii\n",
    "iiiiiiiiiiiiiiii\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    "jjjjjjjjjjjjjjjj\n",
    ),
};

pub static TILE_CLIFF_EDGE_N: SpriteDef = SpriteDef {
    name: "cliff_edge_n",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "kkkkkkkkkkkkkkkk\n",
    "jjjjjjjjjjjjjjjj\n",
    "gggggggggghghggg\n",
    "ggghggggghhggggg\n",
    "gggggggggggggggg\n",
    "gggghhggghggghgg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gggggggggggggggg\n",
    "gghggggggggggggg\n",
    "gggggggggggghggg\n",
    "gggggggggggggggg\n",
    "gggggggggggghhgg\n",
    "gggggggggghhgggg\n",
    "gggggggggggggggg\n",
    ),
};

pub static TILE_CLIFF_EDGE_S: SpriteDef = SpriteDef {
    name: "cliff_edge_s",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "gggggggggggggggg\n",
    "ggggggggghgggggg\n",
    "gggggggggggggggg\n",
    "ggggggghgggggggg\n",
    "gggggggggggggggg\n",
    "ggggggggggggghgg\n",
    "ggggggggghgggggg\n",
    "gggggggggggggggg\n",
    "ggggggggghgghggg\n",
    "ggggggghggghgggg\n",
    "gggggggggggggggg\n",
    "ggggggghgghhgggg\n",
    "ggghgggggggggggg\n",
    "ggggggggghgggghh\n",
    "jjjjjjjjjjjjjjjj\n",
    "kkkkkkkkkkkkkkkk\n",
    ),
};

pub static TILE_CLIFF_EDGE_E: SpriteDef = SpriteDef {
    name: "cliff_edge_e",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "ggggggggggggggjk\n",
    "gggggggggggghgjk\n",
    "ggggggghggggggjk\n",
    "ggggggggggggggjk\n",
    "ggggggggggghggjk\n",
    "hgghggggggggghjk\n",
    "ggggggggggggggjk\n",
    "gggggggggghgggjk\n",
    "hgggggggggggggjk\n",
    "ggggggggggggggjk\n",
    "ggggggggggggghjk\n",
    "hgggggggggggggjk\n",
    "ggggggggggghggjk\n",
    "hgggggggggggggjk\n",
    "ggggggggggggggjk\n",
    "ggggggggggggggjk\n",
    ),
};

pub static TILE_CLIFF_EDGE_W: SpriteDef = SpriteDef {
    name: "cliff_edge_w",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "kjggghgggggggggg\n",
    "kjgggggggggggggg\n",
    "kjghgggggggggggg\n",
    "kjggggggghgggggg\n",
    "kjgggggghggggggg\n",
    "kjghggggghgghhgg\n",
    "kjgggggggggggggg\n",
    "kjggggghgggggggg\n",
    "kjggghgggghggggg\n",
    "kjhhgggggggggggg\n",
    "kjggggggghgggggg\n",
    "kjgggggggggggggg\n",
    "kjgggggggggggggg\n",
    "kjgggggggggggggg\n",
    "kjgggggggggggggg\n",
    "kjgggggggggggggg\n",
    ),
};

pub static TILE_CLIFF_STAIRS: SpriteDef = SpriteDef {
    name: "cliff_stairs",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    "gggggggggggggggg\n",
    "hhhhhhhhhhhhhhhh\n",
    ),
};

pub static TILE_LEDGE_S: SpriteDef = SpriteDef {
    name: "ledge_s",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "ggggggggggggggkj\n",
    "ggggggggggggggkj\n",
    "ggggggggggggggkj\n",
    "gggggghgggggggkj\n",
    "ggggggggggggggkj\n",
    "gghgggggghggghkj\n",
    "ghggggggggggggkj\n",
    "gghgggggggggggkj\n",
    "hhggggggggggggkj\n",
    "gggggggggggghgkj\n",
    "ggggggghggggggkj\n",
    "hgggggggggggggkj\n",
    "gghgggggggggggkj\n",
    "ggggggggggggggkj\n",
    "kkkkkkkkkkkkkkkj\n",
    "jjjjjjjjjjjjjjkj\n",
    ),
};

pub static TILE_LEDGE_N: SpriteDef = SpriteDef {
    name: "ledge_n",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "jjjjjjjjjjjjjjkj\n",
    "kkkkkkkkkkkkkkkj\n",
    "ggggggggggggggkj\n",
    "gggggghgggggggkj\n",
    "ggggggggggggggkj\n",
    "gghgggggghggghkj\n",
    "ghggggggggggggkj\n",
    "gghgggggggggggkj\n",
    "hhggggggggggggkj\n",
    "gggggggggggghgkj\n",
    "ggggggghggggggkj\n",
    "hgggggggggggggkj\n",
    "gghgggggggggggkj\n",
    "ggggggggggggggkj\n",
    "ggggggggggggggkj\n",
    "hgggggggggggggkj\n",
    ),
};

pub static TILE_LEDGE_E: SpriteDef = SpriteDef {
    name: "ledge_e",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "ggggggggggggggkj\n",
    "ggggggggggggggkj\n",
    "ggggggggggggggkj\n",
    "gggggghgggggggkj\n",
    "ggggggggggggggkj\n",
    "gghgggggghggghkj\n",
    "ghggggggggggggkj\n",
    "gghgggggggggggkj\n",
    "hhggggggggggggkj\n",
    "gggggggggggghgkj\n",
    "ggggggghggggggkj\n",
    "hgggggggggggggkj\n",
    "gghgggggggggggkj\n",
    "ggggggggggggggkj\n",
    "ggggggggggggggkj\n",
    "hgggggggggggggkj\n",
    ),
};

pub static TILE_LEDGE_W: SpriteDef = SpriteDef {
    name: "ledge_w",
    w: 16, h: 16, frames: 1,
    grid: concat!(
    "jkggggggggggggkj\n",
    "jkggggggggggggkj\n",
    "jkggggggggggggkj\n",
    "jkgggghgggggggkj\n",
    "jkggggggggggggkj\n",
    "jkhgggggghggghkj\n",
    "jkggggggggggggkj\n",
    "jkhgggggggggggkj\n",
    "jkggggggggggggkj\n",
    "jkgggggggggghgkj\n",
    "jkggggghggggggkj\n",
    "jkggggggggggggkj\n",
    "jkhgggggggggggkj\n",
    "jkggggggggggggkj\n",
    "jkggggggggggggkj\n",
    "jkggggggggggggkj\n",
    ),
};

