//! HUD / toast atlas pieces.

use super::SpriteDef;


pub static UI_HEART_FULL: SpriteDef = SpriteDef {
    name: "heart_full",
    w: 8,
    h: 8,
    frames: 1,
    grid: concat!(
    ".FF.FF..\n",
    "FopFpoF.\n",
    "pppppppF\n",
    "qqqqqqqF\n",
    "FqqqqqF.\n",
    ".FqqqF..\n",
    "..FqF...\n",
    "...F....\n",
    ),
};

pub static UI_HEART_HALF: SpriteDef = SpriteDef {
    name: "heart_half",
    w: 8,
    h: 8,
    frames: 1,
    grid: concat!(
    ".FF.FF..\n",
    "FopFrrF.\n",
    "pppprrrF\n",
    "qqqqrrrF\n",
    "FqqqrrF.\n",
    ".FqqrF..\n",
    "..FqF...\n",
    "...F....\n",
    ),
};

pub static UI_HEART_EMPTY: SpriteDef = SpriteDef {
    name: "heart_empty",
    w: 8,
    h: 8,
    frames: 1,
    grid: concat!(
    ".FF.FF..\n",
    "FrrFrrF.\n",
    "rrrrrrrF\n",
    "rrrrrrrF\n",
    "FrrrrrF.\n",
    ".FrrrF..\n",
    "..FrF...\n",
    "...F....\n",
    ),
};

pub static UI_ENERGY_FRAME: SpriteDef = SpriteDef {
    name: "energy_frame",
    w: 8,
    h: 64,
    frames: 1,
    grid: concat!(
    "QggggggQ\n",
    "QggggggQ\n",
    "QggggggQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QRFFFFRQ\n",
    "QjjjjjjQ\n",
    "QjjjjjjQ\n",
    "QjjjjjjQ\n",
    ),
};

pub static UI_ENERGY_FILL: SpriteDef = SpriteDef {
    name: "energy_fill",
    w: 4,
    h: 60,
    frames: 1,
    grid: concat!(
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "uuuu\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "vvvv\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    "wwww\n",
    ),
};

pub static UI_STYLE_CHIP: SpriteDef = SpriteDef {
    name: "style_chip",
    w: 14,
    h: 14,
    frames: 1,
    grid: concat!(
    ".FFBBBBBBBBFF.\n",
    "FQQQQQQQQQQQQF\n",
    "FQRRRRRRRRRRQF\n",
    "CQRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRQC\n",
    "FQRRRRRRRRRRQF\n",
    "FQQQQQQQQQQQQF\n",
    ".FFBBBBBBBBFF.\n",
    ),
};

pub static UI_ITEM_SLOT: SpriteDef = SpriteDef {
    name: "item_slot",
    w: 22,
    h: 22,
    frames: 1,
    grid: concat!(
    "gggggggggggggggggggggg\n",
    ".QQQQQQQQQQQQQQQQQQQQ.\n",
    ".QFFFFFFFFFFFFFFFFFFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFRRRRRRRRRRRRRRRRFQ.\n",
    ".QFFFFFFFFFFFFFFFFFFQ.\n",
    ".QQQQQQQQQQQQQQQQQQQQ.\n",
    "jjjjjjjjjjjjjjjjjjjjjj\n",
    ),
};

pub static UI_TOAST_PANEL: SpriteDef = SpriteDef {
    name: "toast_panel",
    w: 48,
    h: 16,
    frames: 1,
    grid: concat!(
    "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..\n",
    ".QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ.\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    "CQRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQC\n",
    ".QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ.\n",
    "..CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC..\n",
    ),
};
